/*
Gapstone is a Go binding for the Capstone disassembly library.
For examples, try reading the *_test.go files.

	Library Author: Nguyen Anh Quynh
	Binding Author: Ben Nagy
	License: BSD style - see LICENSE file for details
    (c) 2013 COSEINC. All Rights Reserved.

    THIS FILE WAS AUTO-GENERATED -- DO NOT EDIT!
	Command: ./genconst capstone/bindings/python/capstone/
	Created at: 2025-04-05T12:41:57+00:00

*/

package gapstone

// #cgo LDFLAGS: -lcapstone
// #cgo freebsd CFLAGS: -I/usr/local/include
// #cgo freebsd LDFLAGS: -L/usr/local/lib
// #include <stdlib.h>
// #include <capstone/capstone.h>
import "C"

// For Capstone Engine. AUTO-GENERATED FILE, DO NOT EDIT [arc_const.py]
const (
	ARC_OP_INVALID = C.ARC_OP_INVALID
	ARC_OP_REG = C.ARC_OP_REG
	ARC_OP_IMM = C.ARC_OP_IMM
)

const (
	ARC_REG_INVALID = C.ARC_REG_INVALID
	ARC_REG_BLINK = C.ARC_REG_BLINK
	ARC_REG_FP = C.ARC_REG_FP
	ARC_REG_GP = C.ARC_REG_GP
	ARC_REG_ILINK = C.ARC_REG_ILINK
	ARC_REG_SP = C.ARC_REG_SP
	ARC_REG_R0 = C.ARC_REG_R0
	ARC_REG_R1 = C.ARC_REG_R1
	ARC_REG_R2 = C.ARC_REG_R2
	ARC_REG_R3 = C.ARC_REG_R3
	ARC_REG_R4 = C.ARC_REG_R4
	ARC_REG_R5 = C.ARC_REG_R5
	ARC_REG_R6 = C.ARC_REG_R6
	ARC_REG_R7 = C.ARC_REG_R7
	ARC_REG_R8 = C.ARC_REG_R8
	ARC_REG_R9 = C.ARC_REG_R9
	ARC_REG_R10 = C.ARC_REG_R10
	ARC_REG_R11 = C.ARC_REG_R11
	ARC_REG_R12 = C.ARC_REG_R12
	ARC_REG_R13 = C.ARC_REG_R13
	ARC_REG_R14 = C.ARC_REG_R14
	ARC_REG_R15 = C.ARC_REG_R15
	ARC_REG_R16 = C.ARC_REG_R16
	ARC_REG_R17 = C.ARC_REG_R17
	ARC_REG_R18 = C.ARC_REG_R18
	ARC_REG_R19 = C.ARC_REG_R19
	ARC_REG_R20 = C.ARC_REG_R20
	ARC_REG_R21 = C.ARC_REG_R21
	ARC_REG_R22 = C.ARC_REG_R22
	ARC_REG_R23 = C.ARC_REG_R23
	ARC_REG_R24 = C.ARC_REG_R24
	ARC_REG_R25 = C.ARC_REG_R25
	ARC_REG_R30 = C.ARC_REG_R30
	ARC_REG_R32 = C.ARC_REG_R32
	ARC_REG_R33 = C.ARC_REG_R33
	ARC_REG_R34 = C.ARC_REG_R34
	ARC_REG_R35 = C.ARC_REG_R35
	ARC_REG_R36 = C.ARC_REG_R36
	ARC_REG_R37 = C.ARC_REG_R37
	ARC_REG_R38 = C.ARC_REG_R38
	ARC_REG_R39 = C.ARC_REG_R39
	ARC_REG_R40 = C.ARC_REG_R40
	ARC_REG_R41 = C.ARC_REG_R41
	ARC_REG_R42 = C.ARC_REG_R42
	ARC_REG_R43 = C.ARC_REG_R43
	ARC_REG_R44 = C.ARC_REG_R44
	ARC_REG_R45 = C.ARC_REG_R45
	ARC_REG_R46 = C.ARC_REG_R46
	ARC_REG_R47 = C.ARC_REG_R47
	ARC_REG_R48 = C.ARC_REG_R48
	ARC_REG_R49 = C.ARC_REG_R49
	ARC_REG_R50 = C.ARC_REG_R50
	ARC_REG_R51 = C.ARC_REG_R51
	ARC_REG_R52 = C.ARC_REG_R52
	ARC_REG_R53 = C.ARC_REG_R53
	ARC_REG_R54 = C.ARC_REG_R54
	ARC_REG_R55 = C.ARC_REG_R55
	ARC_REG_R56 = C.ARC_REG_R56
	ARC_REG_R57 = C.ARC_REG_R57
	ARC_REG_R58 = C.ARC_REG_R58
	ARC_REG_R59 = C.ARC_REG_R59
	ARC_REG_R60 = C.ARC_REG_R60
	ARC_REG_R61 = C.ARC_REG_R61
	ARC_REG_R62 = C.ARC_REG_R62
	ARC_REG_R63 = C.ARC_REG_R63
	ARC_REG_STATUS32 = C.ARC_REG_STATUS32
	ARC_REG_ENDING = C.ARC_REG_ENDING
)

const (
	ARC_INS_INVALID = C.ARC_INS_INVALID
	ARC_INS_h = C.ARC_INS_h
	ARC_INS_PBR = C.ARC_INS_PBR
	ARC_INS_ERROR_FLS = C.ARC_INS_ERROR_FLS
	ARC_INS_ERROR_FFS = C.ARC_INS_ERROR_FFS
	ARC_INS_PLDFI = C.ARC_INS_PLDFI
	ARC_INS_STB_FAR = C.ARC_INS_STB_FAR
	ARC_INS_STH_FAR = C.ARC_INS_STH_FAR
	ARC_INS_ST_FAR = C.ARC_INS_ST_FAR
	ARC_INS_ADC = C.ARC_INS_ADC
	ARC_INS_ADC_F = C.ARC_INS_ADC_F
	ARC_INS_ADD_S = C.ARC_INS_ADD_S
	ARC_INS_ADD = C.ARC_INS_ADD
	ARC_INS_ADD_F = C.ARC_INS_ADD_F
	ARC_INS_AND = C.ARC_INS_AND
	ARC_INS_AND_F = C.ARC_INS_AND_F
	ARC_INS_ASL_S = C.ARC_INS_ASL_S
	ARC_INS_ASL = C.ARC_INS_ASL
	ARC_INS_ASL_F = C.ARC_INS_ASL_F
	ARC_INS_ASR_S = C.ARC_INS_ASR_S
	ARC_INS_ASR = C.ARC_INS_ASR
	ARC_INS_ASR_F = C.ARC_INS_ASR_F
	ARC_INS_BCLR_S = C.ARC_INS_BCLR_S
	ARC_INS_BEQ_S = C.ARC_INS_BEQ_S
	ARC_INS_BGE_S = C.ARC_INS_BGE_S
	ARC_INS_BGT_S = C.ARC_INS_BGT_S
	ARC_INS_BHI_S = C.ARC_INS_BHI_S
	ARC_INS_BHS_S = C.ARC_INS_BHS_S
	ARC_INS_BL = C.ARC_INS_BL
	ARC_INS_BLE_S = C.ARC_INS_BLE_S
	ARC_INS_BLO_S = C.ARC_INS_BLO_S
	ARC_INS_BLS_S = C.ARC_INS_BLS_S
	ARC_INS_BLT_S = C.ARC_INS_BLT_S
	ARC_INS_BL_S = C.ARC_INS_BL_S
	ARC_INS_BMSK_S = C.ARC_INS_BMSK_S
	ARC_INS_BNE_S = C.ARC_INS_BNE_S
	ARC_INS_B = C.ARC_INS_B
	ARC_INS_BREQ_S = C.ARC_INS_BREQ_S
	ARC_INS_BRNE_S = C.ARC_INS_BRNE_S
	ARC_INS_BR = C.ARC_INS_BR
	ARC_INS_BSET_S = C.ARC_INS_BSET_S
	ARC_INS_BTST_S = C.ARC_INS_BTST_S
	ARC_INS_B_S = C.ARC_INS_B_S
	ARC_INS_CMP_S = C.ARC_INS_CMP_S
	ARC_INS_CMP = C.ARC_INS_CMP
	ARC_INS_LD_S = C.ARC_INS_LD_S
	ARC_INS_MOV_S = C.ARC_INS_MOV_S
	ARC_INS_EI_S = C.ARC_INS_EI_S
	ARC_INS_ENTER_S = C.ARC_INS_ENTER_S
	ARC_INS_FFS_F = C.ARC_INS_FFS_F
	ARC_INS_FFS = C.ARC_INS_FFS
	ARC_INS_FLS_F = C.ARC_INS_FLS_F
	ARC_INS_FLS = C.ARC_INS_FLS
	ARC_INS_ABS_S = C.ARC_INS_ABS_S
	ARC_INS_ADD1_S = C.ARC_INS_ADD1_S
	ARC_INS_ADD2_S = C.ARC_INS_ADD2_S
	ARC_INS_ADD3_S = C.ARC_INS_ADD3_S
	ARC_INS_AND_S = C.ARC_INS_AND_S
	ARC_INS_BIC_S = C.ARC_INS_BIC_S
	ARC_INS_BRK_S = C.ARC_INS_BRK_S
	ARC_INS_EXTB_S = C.ARC_INS_EXTB_S
	ARC_INS_EXTH_S = C.ARC_INS_EXTH_S
	ARC_INS_JEQ_S = C.ARC_INS_JEQ_S
	ARC_INS_JL_S = C.ARC_INS_JL_S
	ARC_INS_JL_S_D = C.ARC_INS_JL_S_D
	ARC_INS_JNE_S = C.ARC_INS_JNE_S
	ARC_INS_J_S = C.ARC_INS_J_S
	ARC_INS_J_S_D = C.ARC_INS_J_S_D
	ARC_INS_LSR_S = C.ARC_INS_LSR_S
	ARC_INS_MPYUW_S = C.ARC_INS_MPYUW_S
	ARC_INS_MPYW_S = C.ARC_INS_MPYW_S
	ARC_INS_MPY_S = C.ARC_INS_MPY_S
	ARC_INS_NEG_S = C.ARC_INS_NEG_S
	ARC_INS_NOP_S = C.ARC_INS_NOP_S
	ARC_INS_NOT_S = C.ARC_INS_NOT_S
	ARC_INS_OR_S = C.ARC_INS_OR_S
	ARC_INS_SEXB_S = C.ARC_INS_SEXB_S
	ARC_INS_SEXH_S = C.ARC_INS_SEXH_S
	ARC_INS_SUB_S = C.ARC_INS_SUB_S
	ARC_INS_SUB_S_NE = C.ARC_INS_SUB_S_NE
	ARC_INS_SWI_S = C.ARC_INS_SWI_S
	ARC_INS_TRAP_S = C.ARC_INS_TRAP_S
	ARC_INS_TST_S = C.ARC_INS_TST_S
	ARC_INS_UNIMP_S = C.ARC_INS_UNIMP_S
	ARC_INS_XOR_S = C.ARC_INS_XOR_S
	ARC_INS_LDB_S = C.ARC_INS_LDB_S
	ARC_INS_LDH_S = C.ARC_INS_LDH_S
	ARC_INS_J = C.ARC_INS_J
	ARC_INS_JL = C.ARC_INS_JL
	ARC_INS_JLI_S = C.ARC_INS_JLI_S
	ARC_INS_LDB_AB = C.ARC_INS_LDB_AB
	ARC_INS_LDB_AW = C.ARC_INS_LDB_AW
	ARC_INS_LDB_DI_AB = C.ARC_INS_LDB_DI_AB
	ARC_INS_LDB_DI_AW = C.ARC_INS_LDB_DI_AW
	ARC_INS_LDB_DI = C.ARC_INS_LDB_DI
	ARC_INS_LDB_X_AB = C.ARC_INS_LDB_X_AB
	ARC_INS_LDB_X_AW = C.ARC_INS_LDB_X_AW
	ARC_INS_LDB_X_DI_AB = C.ARC_INS_LDB_X_DI_AB
	ARC_INS_LDB_X_DI_AW = C.ARC_INS_LDB_X_DI_AW
	ARC_INS_LDB_X_DI = C.ARC_INS_LDB_X_DI
	ARC_INS_LDB_X = C.ARC_INS_LDB_X
	ARC_INS_LDB = C.ARC_INS_LDB
	ARC_INS_LDH_AB = C.ARC_INS_LDH_AB
	ARC_INS_LDH_AW = C.ARC_INS_LDH_AW
	ARC_INS_LDH_DI_AB = C.ARC_INS_LDH_DI_AB
	ARC_INS_LDH_DI_AW = C.ARC_INS_LDH_DI_AW
	ARC_INS_LDH_DI = C.ARC_INS_LDH_DI
	ARC_INS_LDH_S_X = C.ARC_INS_LDH_S_X
	ARC_INS_LDH_X_AB = C.ARC_INS_LDH_X_AB
	ARC_INS_LDH_X_AW = C.ARC_INS_LDH_X_AW
	ARC_INS_LDH_X_DI_AB = C.ARC_INS_LDH_X_DI_AB
	ARC_INS_LDH_X_DI_AW = C.ARC_INS_LDH_X_DI_AW
	ARC_INS_LDH_X_DI = C.ARC_INS_LDH_X_DI
	ARC_INS_LDH_X = C.ARC_INS_LDH_X
	ARC_INS_LDH = C.ARC_INS_LDH
	ARC_INS_LDI_S = C.ARC_INS_LDI_S
	ARC_INS_LD_AB = C.ARC_INS_LD_AB
	ARC_INS_LD_AW = C.ARC_INS_LD_AW
	ARC_INS_LD_DI_AB = C.ARC_INS_LD_DI_AB
	ARC_INS_LD_DI_AW = C.ARC_INS_LD_DI_AW
	ARC_INS_LD_DI = C.ARC_INS_LD_DI
	ARC_INS_LD_S_AS = C.ARC_INS_LD_S_AS
	ARC_INS_LD = C.ARC_INS_LD
	ARC_INS_LEAVE_S = C.ARC_INS_LEAVE_S
	ARC_INS_LR = C.ARC_INS_LR
	ARC_INS_LSR = C.ARC_INS_LSR
	ARC_INS_LSR_F = C.ARC_INS_LSR_F
	ARC_INS_MAX = C.ARC_INS_MAX
	ARC_INS_MAX_F = C.ARC_INS_MAX_F
	ARC_INS_MIN = C.ARC_INS_MIN
	ARC_INS_MIN_F = C.ARC_INS_MIN_F
	ARC_INS_MOV_S_NE = C.ARC_INS_MOV_S_NE
	ARC_INS_MOV = C.ARC_INS_MOV
	ARC_INS_MOV_F = C.ARC_INS_MOV_F
	ARC_INS_MPYMU = C.ARC_INS_MPYMU
	ARC_INS_MPYMU_F = C.ARC_INS_MPYMU_F
	ARC_INS_MPYM = C.ARC_INS_MPYM
	ARC_INS_MPYM_F = C.ARC_INS_MPYM_F
	ARC_INS_MPY = C.ARC_INS_MPY
	ARC_INS_MPY_F = C.ARC_INS_MPY_F
	ARC_INS_NORMH_F = C.ARC_INS_NORMH_F
	ARC_INS_NORMH = C.ARC_INS_NORMH
	ARC_INS_NORM_F = C.ARC_INS_NORM_F
	ARC_INS_NORM = C.ARC_INS_NORM
	ARC_INS_OR = C.ARC_INS_OR
	ARC_INS_OR_F = C.ARC_INS_OR_F
	ARC_INS_POP_S = C.ARC_INS_POP_S
	ARC_INS_PUSH_S = C.ARC_INS_PUSH_S
	ARC_INS_ROR = C.ARC_INS_ROR
	ARC_INS_ROR_F = C.ARC_INS_ROR_F
	ARC_INS_RSUB = C.ARC_INS_RSUB
	ARC_INS_RSUB_F = C.ARC_INS_RSUB_F
	ARC_INS_SBC = C.ARC_INS_SBC
	ARC_INS_SBC_F = C.ARC_INS_SBC_F
	ARC_INS_SETEQ = C.ARC_INS_SETEQ
	ARC_INS_SETEQ_F = C.ARC_INS_SETEQ_F
	ARC_INS_SEXB_F = C.ARC_INS_SEXB_F
	ARC_INS_SEXB = C.ARC_INS_SEXB
	ARC_INS_SEXH_F = C.ARC_INS_SEXH_F
	ARC_INS_SEXH = C.ARC_INS_SEXH
	ARC_INS_STB_S = C.ARC_INS_STB_S
	ARC_INS_ST_S = C.ARC_INS_ST_S
	ARC_INS_STB_AB = C.ARC_INS_STB_AB
	ARC_INS_STB_AW = C.ARC_INS_STB_AW
	ARC_INS_STB_DI_AB = C.ARC_INS_STB_DI_AB
	ARC_INS_STB_DI_AW = C.ARC_INS_STB_DI_AW
	ARC_INS_STB_DI = C.ARC_INS_STB_DI
	ARC_INS_STB = C.ARC_INS_STB
	ARC_INS_STH_AB = C.ARC_INS_STH_AB
	ARC_INS_STH_AW = C.ARC_INS_STH_AW
	ARC_INS_STH_DI_AB = C.ARC_INS_STH_DI_AB
	ARC_INS_STH_DI_AW = C.ARC_INS_STH_DI_AW
	ARC_INS_STH_DI = C.ARC_INS_STH_DI
	ARC_INS_STH_S = C.ARC_INS_STH_S
	ARC_INS_STH = C.ARC_INS_STH
	ARC_INS_ST_AB = C.ARC_INS_ST_AB
	ARC_INS_ST_AW = C.ARC_INS_ST_AW
	ARC_INS_ST_DI_AB = C.ARC_INS_ST_DI_AB
	ARC_INS_ST_DI_AW = C.ARC_INS_ST_DI_AW
	ARC_INS_ST_DI = C.ARC_INS_ST_DI
	ARC_INS_ST = C.ARC_INS_ST
	ARC_INS_SUB1 = C.ARC_INS_SUB1
	ARC_INS_SUB1_F = C.ARC_INS_SUB1_F
	ARC_INS_SUB2 = C.ARC_INS_SUB2
	ARC_INS_SUB2_F = C.ARC_INS_SUB2_F
	ARC_INS_SUB3 = C.ARC_INS_SUB3
	ARC_INS_SUB3_F = C.ARC_INS_SUB3_F
	ARC_INS_SUB = C.ARC_INS_SUB
	ARC_INS_SUB_F = C.ARC_INS_SUB_F
	ARC_INS_XOR = C.ARC_INS_XOR
	ARC_INS_XOR_F = C.ARC_INS_XOR_F
)

// Group of ARC instructions
const (
	ARC_GRP_INVALID = C.ARC_GRP_INVALID
	ARC_GRP_JUMP = C.ARC_GRP_JUMP
	ARC_GRP_CALL = C.ARC_GRP_CALL
	ARC_GRP_RET = C.ARC_GRP_RET
	ARC_GRP_BRANCH_RELATIVE = C.ARC_GRP_BRANCH_RELATIVE
	ARC_GRP_ENDING = C.ARC_GRP_ENDING
)

